---
abstract: 'Perl module to provide access to the voip.ms API'
author:
  - 'Roy Hooper, E<lt>L<rhooper@toybox.ca><gt>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VOIP-MS
provides:
  VOIP::MS:
    file: lib/VOIP/MS.pm
    version: 0.02
requires:
  Carp: 0
  Moose: 1.15
  MooseX::Params::Validate: 0.14
  SOAP::Lite: 0.710
  perl: v5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
